### ISSUE TITLE
Plotting correlations between liked, Diff-feed, full-read

### ISSUE THREAD

**Issue by Mlth** [Mlth/zeeguu-api#8]
- Plot the correlations on the graph, add new colors for liked, difficulty feedback and full-read. ✅
- Think about how nicenessify the likefunction. ✅ Added topics
- Figure out the correlation of cefr-level / fk-difficulty and difficulty feedback ✅

**Comment by Mlth** [comment]
Explicit likes and difficulty feedback has been plotted separately.
Now we need to find a nice way of showing them, and the difference between them.
Then we should make a legend that explains the graph.

**Comment by oskaitu** [comment]
Made a new function to only plot out when people have given feedback. Ran it once without our "adjustment" for time (left) and once with the adjustment in time (right)


![Image](https://github.com/Mlth/zeeguu-api/assets/100945285/db521bd9-eae2-4ffa-a958-5d8f9cbaeff1)

Not all of them are moved as it could be that a user does not have a cefr_level for the language of the article. But there is definitely a positive argument for the time adjustment we make

**Comment by Mlth** [comment]
We should probably still make a legendary legend @oskaitu

**Comment by Mlth** [comment]
We can now give specific configurations for specific parameters, so we can make multiple different plots with different weights for translations and difficulty
